The phaseless/issue112
SilverNETGroupSGGW/Straciatella pull request #147
Opened 2024-11-06 17:50 UTC by ThePhaseless

2024-11-06 21:24 UTC, matyjb commented
Fajnie to wygląda!
Dodaj tylko jeszcze

ładne info z jakiego studyprogramu pochodzi dany lesson by np prowadzący wiedział z kim ma zajęcia lesson_data_card.dart linia 84
Dodaj ładny tytuł planu zajęć w appbarze schedule_events_app_bar.dart linia 33 zależnie jakim planem jest (możesz scastować odpowiednio do typu LecturerExt czy StudyProgramExt scheduleEventsCubit.state.schedule i powyciągać w ten sposób dane
Zrób git pull bo dodałem switcha by zmieniło mode widoku planu zależnie od tego jakiego typu schedule wyświetlamy (lecturer'a czy studenta)

2024-11-06 21:27 UTC, matyjb commented on lib/presentation/models/lesson_data/lesson_data_desc/lesson_data_desc_lecturers.dart
> +          Text("no_lecturers".tr())
Wygeneruj LocaleKeys przy pomocy komendy i użyj wygenerowanej stałej (tam jest skrypt gen_keys_trans.sh od generowania tego)

2024-11-06 21:28 UTC, matyjb commented on lib/presentation/models/lesson_data/lesson_data_desc/lesson_data_desc_location.dart
> +          "${"location".tr()}: ",
Wygeneruj LocaleKeys przy pomocy komendy i użyj wygenerowanej stałej (tam jest skrypt gen_keys_trans.sh od generowania tego)

2024-11-06 21:28 UTC, matyjb commented on lib/presentation/models/lesson_data/lesson_data_desc/lesson_data_desc_location.dart
> +        label: Text("navigate".tr()),
Wygeneruj LocaleKeys przy pomocy komendy i użyj wygenerowanej stałej (tam jest skrypt gen_keys_trans.sh od generowania tego)

2024-11-06 21:32 UTC, matyjb commented on lib/presentation/models/lesson_data/lesson_data_desc/lesson_data_desc_time_span.dart
> +          ],
Ten linear progress indicator już jest zrobiony ale pionowo. On ma inny wygląd zależnie od tego kiedy wyświetlamy danego lessona. Look lesson_data_time_span.dart

2024-11-06 21:37 UTC, matyjb commented on lib/presentation/models/lesson_data/lesson_data_desc/lesson_data_desc_time_span.dart
> +          style: Theme.of(context).textTheme.bodySmall,
jest tłumaczenie dla tego stringa
```dart
 Text(LocaleKeys.break_span_hours, style: textStyle).plural(
  hours,
  namedArgs: {
    "hours": hours.toString(),
    "minutes": minutes.toString(),
  },
),
```

2024-11-06 21:38 UTC, matyjb requested changes
look komentarze

2024-11-07 23:25 UTC, matyjb requested changes
I jeszcze string w appbarze nie jest zrobiony. Patrz `schedule_screen_app_bar.dart` linia 27

Możesz zacząć od dania tam:
```dart
title: switch ((state.key.type, state.schedule)) {
  (_, null) => const Text(LocaleKeys.loading_schedule).tr(),
  (ScheduleType.lecturer, final LecturerExt schedule) => Text(
      schedule.toString(),
    ), // TODO: make it pretty (maybe two lines?)
  (ScheduleType.studyProgram, final StudyProgramExt schedule) => Text(
      schedule.toString(),
    ), // TODO: make it pretty (maybe two lines?)
  (_, final CollectLessonData schedule) => Text(schedule.toString()),
},
```

Trzeba tam zrobić by to jakoś informacyjnie ładnie wyglądało na jaki my plan w ogóle patrzymy.

Dla lecturera to bym sobie wyobrażał coś w stylu:
Plan Prowadzącego
dr. Alan Turing

A dla studenta
Informatyka rocznik 2020
magisterskie

2024-11-07 23:25 UTC, matyjb commented on lib/presentation/models/lesson_data/lesson_data_tile/lesson_data_card.dart
> +                            style: infoTextTheme,
Tu jeszcze potrzebne info z jakiego studyProgramu i semestru jest ta grupa (Prowadzący patrzący na te grupy by chciał wiedzieć czy ma np. z ISI z semestru 7 Informatyki rocznika 2020 czy z ISI z semestru 5 Informatyki rocznika 2021. Trzeba to rozróżniać

2024-11-07 23:25 UTC, matyjb commented on lib/presentation/models/lesson_data/lesson_data_desc/lesson_data_desc_type.dart
>      );
Czemu kolorek znikną? :(
Może dodaj taka kropkę przed tym stringiem typu w tym właśnie kolorze

2024-11-07 23:30 UTC, ThePhaseless commented on lib/presentation/models/lesson_data/lesson_data_desc/lesson_data_desc_type.dart
>      );
Możliwe że przez przypadek xd

2024-11-10 20:30 UTC, matyjb commented
@ThePhaseless No przecież nie zrobione jeszcze dwie rzeczy

2024-11-10 20:31 UTC, ThePhaseless commented
A dobra nie zauważyłem

2024-11-15 21:22 UTC, merged

2024-11-15 21:23 UTC, matyjb commented
zmergowane częściowo