Mpygruu/issue131
SilverNETGroupSGGW/Straciatella pull request #151
Opened 2024-11-08 21:38 UTC by mpygruu

2024-11-09 01:22 UTC, matyjb requested changes
13 komentarzy 😨😨😨😨😨😨😨 Pechowa liczba...

2024-11-09 01:22 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/schedule_filter_bottom_sheet/schedule_radio_tile.dart
> +  }
Jeżeli to są jakieś jednolinijkowe widgety nie wsadzałbym ich do funckji. Zbędna obfuskacja kodu

2024-11-09 01:22 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/schedule_filter_bottom_sheet/schedule_radio_tile.dart
> +              scheduleEventsCubit.state.schedule! as LecturerExt,
Wykrzyknik i jeszcze type casting. To może się wywalić

Najlepiej od razu handlować takie przypadki i wiedzieć o nich właśnie przy pomocy pattern matchingu w switchu. Możesz edytować tego switcha co wyżej napisałem by jeszcze sprawdzał typ schedula:
```dart
title: switch((scheduleType, scheduleEventsCubit.state.schedule)) {
  (ScheduleType.studyProgram, final StudyProgramExt studyProgram) => cośtam,
  (ScheduleType.lecturer, final LecturerExt lecturerSchedule) => cośtam,
  //.. reszte przypadków do shandle'owania sam vscode ci podpowie
}
```

O patternach możesz poczytać tutaj https://dart.dev/language/patterns
Potężne narzędzie, więc koniecznie zobacz

2024-11-09 01:22 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/schedule_filter_bottom_sheet/schedules_section.dart
> +        : 'lecturer_section_title'.tr();
LocaleKeys

2024-11-09 01:22 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/schedule_filter_bottom_sheet/schedules_section.dart
> +            ),
Tak jak wyżej, Używaj Theme.of(context)

2024-11-09 01:22 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/schedule_filter_bottom_sheet/new_schedule_button.dart
> +        : 'new_lecturer_schedule'.tr();
LocaleKeys

2024-11-09 01:22 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/schedule_filter_bottom_sheet/new_schedule_button.dart
> +          ),
użyj Theme.of(context) na całym stylu tekstu

2024-11-09 01:22 UTC, matyjb commented on lib/data/models/enums.dart
> +enum ScheduleFilter { studyProgram, group }
unused, remove

2024-11-09 11:46 UTC, mpygruu commented on lib/data/models/enums.dart
> +enum ScheduleFilter { studyProgram, group }
Ale jest używany w ScheduleFilterFab i ScheduleFilterOption

2024-11-09 12:11 UTC, mpygruu commented on lib/logic/schedule_filters/schedule_filters_cubit.dart
> +          groups.sort((g1, g2) => g1.name.compareTo(g2.name));
w sensie wykorzystując np. SplayTreeMap? Bo w sumie te firstWhere też można by uznać za traverse drzewa na siłę

2024-11-09 12:21 UTC, mpygruu commented on lib/logic/schedule_filters/schedule_filters_cubit.dart
> +          groups.sort((g1, g2) => g1.name.compareTo(g2.name));
lol dobra, już się komórki zderzyły

2024-11-09 12:29 UTC, mpygruu commented
Poprawione

2024-11-09 13:54 UTC, matyjb requested changes
.

2024-11-09 13:54 UTC, matyjb commented on lib/data/models/enums.dart
> +enum ScheduleFilter { studyProgram, group }
A rzeczywiście, vscode mi za pierwszym razem nie pokazał tych odniesień. To i tak ja bym to nazwał jakoś inaczaj. Słowo Filter jest tu mylące w kontekscie studyProgramu. Albo w ogóle te dwa guziki od tego faba rozdzielił na dwa inne widgety bez tej flagi. Bo aktualnie to masz takie właśnie dwa widgety w jednym

2024-11-09 13:54 UTC, matyjb commented on lib/logic/schedule_filters/schedule_filters_cubit.dart
> +              .toList();
Mi zależało byś się pozbył tego odniesienia do cubita. Wszystko jest w byStudentGroups. Też wtedy będziesz mógł uprościć tego if'a wyżej

2024-11-09 13:54 UTC, matyjb commented on lib/logic/schedule_filters/schedule_filters_cubit.dart
> +          groups.sort((g1, g2) => g1.name.compareTo(g2.name));
Pamiętasz jak dałem sugestię by zamiast sorta zrobić jednym forem z kandydatem najlepszym i go podmieniąjąc lub nie przy każdym passie tego for'a? Spoko jakbyś właśnie się pozbył tego sorta

2024-11-09 13:54 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/group_filter_bottom_sheet/group_semester.dart
> +            '${LocaleKeys.semester.tr()} ${studySemester.semester}',
A może by ci się udało to wsadzić jako jedno tłumaczenie z argumentami. Nie we wszystkich językach wkońcu czyta się od lewej do prawej czy też nie ma tej samej kolejności wyrazów. O argumentach możesz poczytać w readme https://pub.dev/packages/easy_localization

2024-11-09 13:54 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/group_filter_bottom_sheet/group_filter_bottom_sheet.dart
> +        .schedule!
wykrzyknik, lepiej użyj ? i jako default np pustą listę

2024-11-09 20:29 UTC, matyjb requested changes

2024-11-09 20:29 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/schedule_filter_fab/schedule_filter_fab_option.dart
> +class ScheduleFilterFabOption extends StatelessWidget {
Daj jakąś inną nazwę, bo ten Filter jest mylący. My nie filtrujemy scheduli tutaj, a raczej wybieramy

2024-11-09 20:43 UTC, matyjb commented on lib/logic/schedule_filters/schedule_filters_cubit.dart
> +          groups.sort((g1, g2) => g1.name.compareTo(g2.name));
Zobacz ostatniego mojego commita na tym branchu o co mi chodziło

2024-11-10 00:13 UTC, matyjb approved these changes

2024-11-10 00:13 UTC, merged