Mpygruu/issue127
SilverNETGroupSGGW/Straciatella pull request #153
Opened 2024-11-12 21:59 UTC by mpygruu

2024-11-12 23:11 UTC, mpygruu commented
Jeszcze jedno TODO: dodać non-breaking space żeby "i" przeskoczyło do nowej linii.

2024-11-12 23:23 UTC, mpygruu commented
Chociaż to na koniec może osobny issue żeby w każdym stringu gdzie trzeba to dodać non breaking space

2024-11-14 22:52 UTC, matyjb requested changes
Tylko ten pomysł z inkwellami, reszta pięknie

2024-11-14 22:52 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/new_lecturer_schedule_button.dart
> +    return GestureDetector(
A może coś pokombinować z InkWelle, by mieć animacje wciskania

2024-11-14 22:52 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/new_student_schedule_button.dart
> +    return GestureDetector(
To samo co wyżej, z tym InkWellem

2024-11-15 21:16 UTC, merged