Poprawki designu
SilverNETGroupSGGW/Straciatella pull request #156
Opened 2024-11-20 19:15 UTC by mpygruu

To co wyłapałem poniżej, w razie sprzeciwu albo jak coś jeszcze jest do poprawy to możemy od razu tutaj.

- [x] W ustawieniach spacing między tytułem a początkiem strony jest przeolbrzymi, może zmniejszyć lub w ogóle usunąć
- [x] W przyciskach w WelcomeScreen — „Dalej” a nie „Następny”, „Wstecz” a nie „Poprzedni”, "Koniec" a nie "Zakończ"
- [x] Więcej odstępu między kartką zajęć a tekstem z minutami przerwy
- [x] Zrobić większą kartkę i ew. dodać info o tym czy to wykład czy laby w subtitle
- [x] W widoku FavedScheduleScreen wszystko jest tak pościskane — pododawać większe odstępy, jest na to mnóstwo miejsca, będzie czytelniej
- [x] Sortowanie grup w szczegółach konkretnych zajęć z kalendarza
- [x] Wyszukiwarka w NewLecturerSchedule jest ciut za nisko
- [x] Dodać skróty tytułów naukowych
- [x] W WelcomeScreen poprawić odstępy między tekstami i ikonkami
- [x] W WelcomeScreen zmienić styl przycisku Next z Filled na FilledTonal
- [x] W NewLecturerScreen oraz NewScheduleScreen zmienić styl przycisku "Dodaj" na filled
- [x] Poprawić wyświetlanie przerwy gdy jest pełna godzina i 0 minut
- [x] Poprawki tłumaczeń w widgetach związanych z wyborem nowego planu studenta
- [x] Zmienić email na instytut w ListTile prowadzącego przy wyborze nowego planu prowadzącego
- [x] W widoku zmiany widocznego planu zmienić wyświetlaną nazwę z skrótowego np. IiE lic. stac. 77/78 na coś ładniejszego

2024-11-24 19:12 UTC, matyjb commented on lib/presentation/models/lesson_data/lesson_data_desc/lesson_data_desc_time_span.dart
> +          )}",
Albo w ogóle zrób tak samo jak z break_span (te trzy przypadki zależnie czy godziny lub minuty są równe zero

2024-11-24 19:23 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/schedule_events_screens/schedule_screen_app_bar.dart
> +      const Size.fromHeight(kToolbarHeight + 40 + 14 + 16 + 12);
Też komentarz

2024-11-24 19:24 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/schedule_events_screens/schedule_title_app_bar/schedule_title_app_bar_lecturer.dart
> +
To samo z tą statyczną mapą

2024-11-24 19:25 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/schedule_filter_bottom_sheet/schedule_radio_tile.dart
> +      '${'degree_abbr.${StringUtils.camelCaseToLowerUnderscore(lecturer.academicDegree)}'.tr()} ${lecturer.firstName} ${lecturer.surName}';
To samo z tą statczną mapą

2024-11-24 19:44 UTC, matyjb commented
![image](https://github.com/user-attachments/assets/578fbf05-e546-47c1-ab80-8c49cde60495)
 Tutaj miałeś:
 > W widoku zmiany widocznego planu zmienić wyświetlaną nazwę z skrótowego np. IiE lic. stac. 77/78 na coś ładniejszego

Chyba coś nie pykło ;)

2024-11-24 19:46 UTC, matyjb commented
A jeszcze to przy okazji, bo to w sumie też poprawka designu. Te guziki od faba nie są aligned (na webie przynajmniej)
![image](https://github.com/user-attachments/assets/03b6cfbc-0177-490a-9a11-9f9b6d22b96d)

2024-11-29 01:07 UTC, matyjb commented on lib/presentation/screens/new_schedule/widgets/student_schedule/widgets/student_schedule_bottom_app_bar.dart
> +        : '${'pick'.tr()} ${levelName.camelToSnake().tr().toLowerCase()}';
Hm, tu w sumie trzeba wrzucić tego level name'a jako argument tłumaczenia od pick, bo może i w angielskim i polskim to jest "Pick X" i "Wybierz X", ale może w jakimś języku będzie "X _wybierz_"

2024-11-29 08:27 UTC, mpygruu commented on lib/presentation/screens/new_schedule/widgets/student_schedule/widgets/student_schedule_bottom_app_bar.dart
> +        : '${'pick'.tr()} ${levelName.camelToSnake().tr().toLowerCase()}';
a racja, zrobi się. Jeszcze wczoraj nie zdążyłem wszystkiego machnąć to reszte też

2024-11-29 12:12 UTC, mpygruu commented
Zostało mi tylko dodanie komentarzy do tych sumowanych liczb i trochę pozmieniać design info o budynki, piętrze i sali ale to zrobię już dzisiaj wieczorem.

2024-11-29 23:24 UTC, matyjb requested changes

2024-11-29 23:24 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/new_lecturer_schedule_button.dart
> +              ),
Użyj [ConstrainedBox](https://api.flutter.dev/flutter/widgets/ConstrainedBox-class.html) i tam nadaj maxWidth. SizedBox może zrobić overflowa przy zbyt małej szerokości

2024-11-29 23:24 UTC, matyjb commented on lib/presentation/screens/schedule/widgets/new_student_schedule_button.dart
> +              ),
Tak jak wyżej, ConstrainedBox

2024-11-30 15:12 UTC, matyjb approved these changes

2024-11-30 15:12 UTC, merged